FROM ubuntu
RUN apt update -y; apt upgrade -y; \
    apt install nginx curl wget php-fpm -y; \
    rm -rf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

COPY ../default /etc/nginx/sites-available/default
RUN ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

COPY ../port /usr/bin/port
COPY ../new-site /usr/bin/new-site
RUN chmod +x /usr/bin/port /usr/bin/new-site

RUN curl -fOL https://github.com/coder/code-server/releases/download/v4.11.0/code-server_4.11.0_amd64.deb
RUN dpkg -i code-server_4.11.0_amd64.deb

CMD ["sh", "-c", "service php7.4-fpm start; nginx -g 'daemon off;' & code-server --auth none --host 0.0.0.0"]
