FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    tzdata && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    apt-get install -y nginx curl wget php-fpm && \
    rm -rf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

COPY default /etc/nginx/sites-available/default
RUN ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
RUN ln -s /etc/nginx /settings
RUN mkdir -p /sites/default

COPY port /usr/bin/port
COPY new-site /usr/bin/new-site
RUN chmod +x /usr/bin/port /usr/bin/new-site

RUN curl -fOL https://github.com/coder/code-server/releases/download/v4.12.0/code-server_4.12.0_arm64.deb
RUN dpkg -i code-server_4.12.0_arm64.deb

CMD ["sh", "-c", "service php8.1-fpm start; nginx -g 'daemon off;' & code-server --auth none --host 0.0.0.0"]
