services:
  website:
    restart: unless-stopped
    container_name: A-website
    network_mode: host
    volumes:
      - web-code:/code-settings
      - web-sites:/sites
      - web-settings:/settings
    image: thegreatestgiant/website:latest
volumes:
  web-code:
  web-sites:
  web-settings:
