#!/bin/bash

if [ -z "$1" ] || [ "$1" = "-h" ]; then
  echo "Usage: new-site [domain]"
  echo "Options:"
  echo "  -h    Show this help message"
  echo "  -p    Specify a custom port (optional)"
  exit 2
fi

PORT=""
DOMAIN=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      echo "Usage: new-site [domain] [-p port]"
      echo "Options:"
      echo "  -h, --help    Show this help message"
      echo "  -p, --port    Specify a custom port (optional)"
      exit 2
      ;;
    -p|--port)
      if [[ -z "$2" || "$2" =~ ^- ]]; then
        echo "Error: Please provide a valid port number after the -p option."
        exit 2
      fi
      PORT="$2"
      shift 2
      ;;
    *)
      if [[ -z "$DOMAIN" ]]; then
        DOMAIN="$1"
      else
        echo "Error: Unknown option or argument - $1"
        exit 2
      fi
      shift
      ;;
  esac
done

if [[ -z "$PORT" ]]; then
  PORT=$(($(/usr/bin/port)+1))
fi

config_file="/settings/sites-available/$DOMAIN"

if ! touch "$config_file"; then
  echo "Failed to create config file"
  exit 3
fi

if "$1" != "-p"; then
  cat << EOF > "$config_file"
  server {
          listen $PORT;
          root /sites/$DOMAIN;
          index index.php index.html index.htm;
          server_name $DOMAIN;
          location / {
                  try_files \$uri \$uri/ =404;
          }
          location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/run/php/php8.1-fpm.sock;
          }
  }
EOF
fi

if ! ln -s "$config_file" /etc/nginx/sites-enabled; then
  echo "Failed to enable config file"
  exit 4
fi

if [ ! -d "/sites/$DOMAIN" ];then
    mkdir /sites/$DOMAIN
fi
touch /sites/$DOMAIN/index.html

service nginx reload
service php8.1-fpm reload
nginx -t

echo "Done!"
