FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
COPY spoof /usr/bin
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends ca-certificates nginx curl nano certbot python3-certbot-nginx tzdata && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    ln -s /var/www/html /sites && \
    ln -s /etc/nginx /settings && \
    ARCH=$(if [ $(uname -m) = "aarch64" ]; then echo "arm64"; elif [ $(uname -m) = "x86_64" ]; then echo "amd64"; else echo $(uname -m); fi) && \
    curl -fOL https://github.com/coder/code-server/releases/download/v4.12.0/code-server_4.12.0_${ARCH}.deb && \
    dpkg -i code-server_4.12.0*.deb && \
    rm code-server* && \
    chmod +x /usr/bin/spoof
ADD code-server.tar.gz /root/.local/share    

CMD ["sh", "-c", "nginx -g 'daemon off;' & code-server --auth none --host 0.0.0.0"]