#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: spoof [domain]"
  echo "Options:"
  echo "  -h    Show this help message"
  echo "  -i    Shows information about spoof"
  exit 2
fi

if [ "$1" = "-h" ]; then
  echo "Usage: spoof [domain]"
  echo "Options:"
  echo "  -h    Show this help message"
  echo "  -i    Shows information about spoof"
  exit 3
fi

if [ "$1" = "-i" ]; then
  echo "Usage: spoof [domain]"
  echo "Info:"
  echo "    This just runs runs 'certbot --non-interactive --redirect --agree-tos --nginx -m admin@gmail.com -d'"
  exit 4
fi

certbot --non-interactive --redirect --agree-tos --nginx -m admin@gmail.com -d $1