FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    tzdata && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    apt-get install -y nginx ssh zip unzip curl nano php-fpm certbot python3-certbot-nginx && \
    rm -rf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default && \
    mkdir -p /sites/default && touch /sites/default/index.html
ADD default /etc/nginx/sites-available
RUN ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default && \
    ln -s /etc/nginx /settings

RUN ARCH=$(if [ $(uname -m) = "aarch64" ]; then echo "arm64"; elif [ $(uname -m) = "x86_64" ]; then echo "amd64"; else echo $(uname -m); fi) && \
    curl -fOL https://github.com/coder/code-server/releases/download/v4.12.0/code-server_4.12.0_${ARCH}.deb && \
    dpkg -i code-server_4.12.0*.deb
ADD code-server.tar.gz /root/.local/share
RUN tar -xzf /root/.local/share/code-server.tar.gz && \
    rm code-server*

CMD service php8.1-fpm start && nginx -g 'daemon off;' && code-server --auth none --host 0.0.0.0
